'''线性代数'''

In [1]:
import torch

In [6]:
x=torch.tensor([3.0])
y=torch.tensor([2.0])
x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [15]:
x=torch.arange(20).reshape(4,5)
print(x.T)
x.T
print(x.reshape(5,4))


tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


In [14]:
x.T==x.reshape(5,4)

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False,  True]])

In [17]:
B=torch.arange(24).reshape(2,3,4)
B

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [20]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()
B
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [27]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X
a*X
X.cumsum(axis=2)


tensor([[[ 0,  1,  3,  6],
         [ 4,  9, 15, 22],
         [ 8, 17, 27, 38]],

        [[12, 25, 39, 54],
         [16, 33, 51, 70],
         [20, 41, 63, 86]]])

In [28]:
A=torch.arange(20).reshape(5,4)
B=torch.arange(12).reshape(4,3)
torch.mm(A,B)

tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262],
        [258, 312, 366],
        [330, 400, 470]])

In [39]:
a= torch.ones(2,5,4)
a.sum(1).shape
a.sum([1,2])

tensor([20., 20.])