In [51]:
import torch
import numpy as np

In [6]:
x=torch.arange(15)
print(x)
print(x.shape)
x.numel()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
torch.Size([15])


15

In [10]:
X=x.reshape(3,5)
print(X)
print(X.reshape(5,3))

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])


In [11]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
torch.zeros(2,3,4,5)

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])

$x_1$

###加减乘除

In [16]:
x=torch.tensor([1.0,2.0,4.0,8.0])
y=torch.tensor([2,2,2,2])
print(x**y)

tensor([ 1.,  4., 16., 64.])


把多个张量连接在一起

In [35]:
x=torch.arange(12,dtype=torch.float32).reshape(3,4)
y=10*torch.rand(12,dtype=torch.float32).reshape(3,4)
print(x)
print(y)
print()

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[6.4476, 6.3490, 4.5303, 0.8912],
        [9.1753, 2.6844, 0.1459, 8.8363],
        [8.0954, 7.1385, 6.7344, 6.8069]])



In [23]:
torch.concat((x,y),dim=1)
torch.concat((x,y),dim=0)

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
        [ 4.0000,  5.0000,  6.0000,  7.0000],
        [ 8.0000,  9.0000, 10.0000, 11.0000],
        [ 0.9903,  7.7888,  5.0608,  2.7348],
        [ 0.4623,  0.7470,  0.9321,  6.9755],
        [ 8.9173,  3.7116,  3.0681,  7.9701]])

In [24]:
x==y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [28]:
print(x.sum())
print(y.sum())

tensor(66.)
tensor(49.3588)


广播机制

In [33]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [34]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

元素访问

In [45]:
x[1:3]
x[1,2]
x[:3]
x[0:2,2:4]=99
x

tensor([[ 0.,  1., 99., 99.],
        [ 4.,  5., 99., 99.],
        [ 8.,  9., 10., 11.]])

In [48]:
A=x.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

数据预处理
1.创建一个人工数据集，储存在csv（逗号分隔值）文件 

In [ ]:
import os
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('4,NA,5600\n')
    f.write('2,NA,456\n')
    f.write('NA,NA,15156\n')

In [54]:
import pandas as pd

In [61]:
data =pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       4.0   NaN    5600
2       2.0   NaN     456
3       NaN   NaN   15156

In [101]:
inputs, outputs = data.iloc[:,0:2],data.iloc[:,2]
numeric_col = inputs.select_dtypes(include=['int', 'float']).columns
inputs[numeric_col] = inputs[numeric_col].fillna(inputs[numeric_col].mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       4.0   NaN
2       2.0   NaN
3       3.0   NaN


In [102]:
inputs=pd.get_dummies(inputs,dummy_na=True,dtype=int)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       4.0           0          1
2       2.0           0          1
3       3.0           0          1


In [103]:
import torch
X,y=torch.tensor(inputs.values),torch.tensor(outputs.values)
X,y

(tensor([[3., 1., 0.],
         [4., 0., 1.],
         [2., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500,   5600,    456,  15156]))